apiVersion: v1
kind: Service
metadata:
  name: openclaw
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/part-of: open-os
spec:
  type: ClusterIP
  selector:
    app: openclaw
  ports:
    - port: 11434
      targetPort: api
      protocol: TCP
      name: api
---
apiVersion: v1
kind: Service
metadata:
  name: dlp-proxy
  namespace: openclaw
  labels:
    app.kubernetes.io/name: dlp-proxy
    app.kubernetes.io/part-of: open-os
  annotations:
    cloud.google.com/backend-config: '{"default": "dlp-proxy-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: dlp-proxy
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: openclaw
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/part-of: open-os
  annotations:
    cloud.google.com/backend-config: '{"default": "openclaw-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
